#include "project_internals.hpp"
#include <cctype>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#if defined(__unix__) || defined(__APPLE__)
#include <spawn.h>
#include <sys/wait.h>
#define KYNA_CLI_POSIX 1
extern char **environ;
#endif

namespace kyna::cli {
namespace {
bool write(const fs::path &path, std::string_view contents, std::string &error) {
  return projectWrite(path, contents, error);
}
std::string shellQuote(const std::string &value) { return projectShellQuote(value); }

// Runs a program with an explicit argument vector and waits for completion.
// Unlike std::system, no shell interprets the arguments, so values such as
// dependency URLs or cache paths can never inject additional commands.
int runArgv(const std::string &program, const std::vector<std::string> &args) {
#if defined(KYNA_CLI_POSIX)
  std::vector<std::string> storage;
  storage.reserve(args.size() + 1);
  storage.push_back(program);
  for (const auto &argument : args)
    storage.push_back(argument);
  std::vector<char *> argv;
  argv.reserve(storage.size() + 1);
  for (auto &entry : storage)
    argv.push_back(entry.data());
  argv.push_back(nullptr);

  posix_spawn_file_actions_t actions;
  posix_spawnattr_t attributes;
  if (posix_spawn_file_actions_init(&actions) != 0 || posix_spawnattr_init(&attributes) != 0)
    return -1;
  pid_t child = -1;
  const int spawnError =
      posix_spawn(&child, program.c_str(), &actions, &attributes, argv.data(), environ);
  posix_spawnattr_destroy(&attributes);
  posix_spawn_file_actions_destroy(&actions);
  if (spawnError != 0)
    return -1;
  int status = 0;
  if (waitpid(child, &status, 0) < 0)
    return -1;
  return WIFEXITED(status) ? WEXITSTATUS(status) : 128;
#else
  (void)program;
  (void)args;
  return -1;
#endif
}
} // namespace

fs::path cacheRoot() {
#if defined(_WIN32)
  if (const char *value = std::getenv("LOCALAPPDATA"))
    return fs::path(value) / "Kyna/cache";
#elif defined(__APPLE__)
  if (const char *value = std::getenv("HOME"))
    return fs::path(value) / "Library/Caches/Kyna";
#else
  if (const char *value = std::getenv("XDG_CACHE_HOME"))
    return fs::path(value) / "kyna";
  if (const char *value = std::getenv("HOME"))
    return fs::path(value) / ".cache/kyna";
#endif
  return fs::temp_directory_path() / "kyna-cache";
}

toml::table loadManifest(const fs::path &root, std::string &error) {
  try {
    return toml::parse_file((root / "kyna.toml").string());
  } catch (const toml::parse_error &e) {
    error = e.description();
    return {};
  }
}

bool saveManifest(const fs::path &root, const toml::table &table, std::string &error) {
  std::ostringstream text;
  text << table;
  text << '\n';
  return write(root / "kyna.toml", text.str(), error);
}

int runDependencies(const Options &options, std::ostream &output, std::ostream &errors) {
  const auto root = discoverProject();
  if (root.empty()) {
    errors << "ky: no kyna.toml found\n";
    return 2;
  }
  std::string error;
  auto manifest = loadManifest(root, error);
  if (!error.empty()) {
    errors << "ky: " << error << '\n';
    return 2;
  }
  auto *deps = manifest["dependencies"].as_table();
  if (!deps) {
    manifest.insert("dependencies", toml::table{});
    deps = manifest["dependencies"].as_table();
  }
  if (options.command == Command::Add) {
    toml::table dependency;
    if (!options.dependencyGit.empty()) {
      dependency.insert("git", options.dependencyGit);
      if (!options.dependencyRevision.empty())
        dependency.insert("rev", options.dependencyRevision);
    } else
      dependency.insert("path", options.dependencyPath);
    deps->insert_or_assign(options.dependencyName, std::move(dependency));
    if (!saveManifest(root, manifest, error)) {
      errors << "ky: " << error << '\n';
      return 2;
    }
  } else if (options.command == Command::Remove) {
    if (!deps->erase(options.dependencyName)) {
      errors << "ky: dependency '" << options.dependencyName << "' does not exist\n";
      return 2;
    }
    if (!saveManifest(root, manifest, error)) {
      errors << "ky: " << error << '\n';
      return 2;
    }
  }
  std::ostringstream lock;
  lock << "# Generated by ky. Do not edit.\nversion = 1\n\n";
  for (const auto &[name, node] : *deps) {
    const auto *dependency = node.as_table();
    if (!dependency)
      continue;
    lock << "[[package]]\nname = \"" << name.str() << "\"\n";
    if (auto path = (*dependency)["path"].value<std::string>()) {
      const auto resolved = fs::weakly_canonical(root / *path);
      lock << "source = \"path+" << resolved.generic_string()
           << "\"\nchecksum = \"local\"\n\n";
    } else if (auto git = (*dependency)["git"].value<std::string>()) {
      const auto requested = (*dependency)["rev"].value_or(std::string("HEAD"));
      const auto cache = cacheRoot() / "git" / std::string(name.str());
      fs::create_directories(cache.parent_path());
      if (!fs::exists(cache / ".git")) {
        const auto cloneArgs = std::vector<std::string>{"clone", "--quiet", "--no-checkout",
                                                        *git, cache.string()};
        if (runArgv("git", cloneArgs) != 0) {
          errors << "ky install: failed to clone " << *git << '\n';
          return 2;
        }
      }
      (void)runArgv("git", {"-C", cache.string(), "fetch", "--quiet", "--tags", "origin"});
      const auto checkout =
          runArgv("git", {"-C", cache.string(), "checkout", "--quiet", "--detach", requested});
      if (checkout != 0) {
        errors << "ky install: cannot resolve " << requested << '\n';
        return 2;
      }
      const auto revFile = cache / ".kyna-revision";
      // Capture the resolved revision by spawning with the shell only to
      // redirect output, which is safe because all arguments are verbatim.
      const auto revisionShell =
          "git -C " + shellQuote(cache.string()) + " rev-parse HEAD > " +
          shellQuote(revFile.string());
      if (std::system(revisionShell.c_str()) != 0)
        return 2;
      std::string revision = readInput(revFile.string(), std::cin, error);
      while (!revision.empty() &&
             std::isspace(static_cast<unsigned char>(revision.back())))
        revision.pop_back();
      lock << "source = \"git+" << *git << "\"\nrevision = \"" << revision
           << "\"\nchecksum = \"git-tree:" << revision << "\"\n\n";
    }
  }
  const auto lockPath = root / "kyna.lock";
  std::string existing;
  if (fs::exists(lockPath))
    existing = readInput(lockPath.string(), std::cin, error);
  if (options.locked && existing != lock.str()) {
    errors << "ky install --locked: kyna.toml and kyna.lock disagree\n";
    return 2;
  }
  if (!options.locked && !write(lockPath, lock.str(), error)) {
    errors << "ky: " << error << '\n';
    return 2;
  }
  if (!options.quiet)
    output << (options.command == Command::Remove ? "Removed dependency" : "Dependencies resolved")
           << "\n";
  return 0;
}

} // namespace kyna::cli
