// Completion vocabulary and namespace member catalogs.
const vscode = require('vscode');
const wordCompletions = [
  ['var', vscode.CompletionItemKind.Keyword, 'Mutable, type-locked binding', 'var ${1:name} = ${0:value};'],
  ['const', vscode.CompletionItemKind.Keyword, 'Immutable binding', 'const ${1:name} = ${0:value};'],
  ['fn', vscode.CompletionItemKind.Keyword, 'Function declaration', 'fn ${1:name}(${2:arg}: ${3:type}): ${4:void} {\n\t$0\n}'],
  ['class', vscode.CompletionItemKind.Class, 'Class declaration', 'class ${1:Name} {\n\t$0\n}'],
  ['intf', vscode.CompletionItemKind.Interface, 'Interface declaration (extends/generics/optional props)', 'intf ${1:Name}${2:<T>}${3: extends ${4:Parent}} {\n\t${5:prop}: ${6:type};\n\t$0\n}'],
  ['type', vscode.CompletionItemKind.Keyword, 'Compile-time type alias', 'type ${1:Name} = ${2:int};'],
  ['import-type', vscode.CompletionItemKind.Keyword, 'Import a compile-time contract', 'import type { ${2:Name} } from \"${1:./t.ky}\";'],
  ['export-type', vscode.CompletionItemKind.Keyword, 'Re-export compile-time contracts', 'export type { ${1:Name} };'],
  ['import', vscode.CompletionItemKind.Keyword, 'Namespace import', 'import * as ${2:module} from "${1:./module.kyna}";'],
  ['import-named', vscode.CompletionItemKind.Keyword, 'Named import', 'import { ${2:a}, ${3:b} } from "${1:./module.kyna}";'],
  ['import-default', vscode.CompletionItemKind.Keyword, 'Default import', 'import ${2:name} from "${1:./module.kyna}";'],
  ['import-legacy', vscode.CompletionItemKind.Keyword, 'Legacy namespace import', 'import "${1:./module.kyna}" as ${2:module};'],
  ['export', vscode.CompletionItemKind.Keyword, 'Export a named declaration', 'export ${0}'],
  ['export-default', vscode.CompletionItemKind.Keyword, 'Default export', 'export default ${0}'],
  ['export-list', vscode.CompletionItemKind.Keyword, 'Export list', 'export { ${1:a}, ${2:b} };'],
  ['if', vscode.CompletionItemKind.Keyword, 'Conditional', 'if (${1:condition}) {\n\t$0\n}'],
  ['while', vscode.CompletionItemKind.Keyword, 'While loop', 'while (${1:condition}) {\n\t$0\n}'],
  ['else', vscode.CompletionItemKind.Keyword, 'Alternative branch'],
  ['break', vscode.CompletionItemKind.Keyword, 'Exit the current or named loop', 'break${1:};'],
  ['continue', vscode.CompletionItemKind.Keyword, 'Continue the current or named loop', 'continue${1:};'],
  ['loop', vscode.CompletionItemKind.Keyword, 'C-style loop', 'loop (var ${1:i} = 0; ${1:i} < ${2:count}; ${1:i} = ${1:i} + 1) {\n\t$0\n}'],
  ['switch', vscode.CompletionItemKind.Keyword, 'Switch on a value', 'switch (${1:value}) {\n\tcase ${2:case}: {\n\t\t$0\n\t}\n\tdefault: {\n\t}\n}'],
  ['case', vscode.CompletionItemKind.Keyword, 'Switch case arm'],
  ['default', vscode.CompletionItemKind.Keyword, 'Fallback switch arm'],
  ['await', vscode.CompletionItemKind.Keyword, 'Wait for an async result', 'await ${0:expression}'],
  ['match', vscode.CompletionItemKind.Keyword, 'Match expression', 'match (${1:value}) {\n\t${2:pattern} => ${3:result};\n\t_ => ${0:fallback};\n}'],
  ['try', vscode.CompletionItemKind.Keyword, 'Handle a typed Error', 'try {\n\t$1\n} catch (${2:error}) {\n\t$3\n} finally {\n\t$0\n}'],
  ['catch', vscode.CompletionItemKind.Keyword, 'Catch a typed Error value'],
  ['finally', vscode.CompletionItemKind.Keyword, 'Always execute cleanup code'],
  ['throw', vscode.CompletionItemKind.Keyword, 'Raise an Error or value', 'throw ${0:error};'],
  ['return', vscode.CompletionItemKind.Keyword, 'Return from a function', 'return ${0:value};'],
  ['new', vscode.CompletionItemKind.Constructor, 'Construct a class', 'new ${1:Class}($0)'],
  ['init', vscode.CompletionItemKind.Constructor, 'Class constructor', 'init(${1:arg}: ${2:type}) {\n\t$0\n}'],
  ['public', vscode.CompletionItemKind.Keyword, 'Public member visibility'],
  ['private', vscode.CompletionItemKind.Keyword, 'Private member visibility'],
  ['protected', vscode.CompletionItemKind.Keyword, 'Protected member visibility'],
  ['static', vscode.CompletionItemKind.Keyword, 'Class-level member'],
  ['override', vscode.CompletionItemKind.Keyword, 'Explicit method override'],
  ['final', vscode.CompletionItemKind.Keyword, 'Prevent extension or override'],
  ['abstract', vscode.CompletionItemKind.Keyword, 'Abstract class or method'],
  ['implements', vscode.CompletionItemKind.Keyword, 'Declare interface conformance'],
  ['extends', vscode.CompletionItemKind.Keyword, 'Declare a parent class'],
  ['self', vscode.CompletionItemKind.Variable, 'Current receiver'],
  ['super', vscode.CompletionItemKind.Variable, 'Parent receiver'],
  ['true', vscode.CompletionItemKind.Value, 'Boolean true'],
  ['false', vscode.CompletionItemKind.Value, 'Boolean false'],
  ['null', vscode.CompletionItemKind.Value, 'Null value'],
  ...['int', 'float', 'num', 'str', 'char', 'bool', 'void', 'any'].map(word =>
    [word, vscode.CompletionItemKind.TypeParameter, `Kyna ${word} type`]),
  ...['print', 'typeOf', 'len', 'push', 'pop', 'keys', 'readFile', 'writeFile', 'processRun',
    'readJsonFile', 'writeJsonFile', 'createDirectory', 'fileExists', 'removePath',
    'listDirectory', 'processEnv', 'sleep', 'wait', 'httpGet', 'fetch', 'fetchResult', 'build',
    'collectGarbage', 'gcStats',
    'log', 'logColor', 'console', 'error', 'filter', 'sort', 'bubbleSort', 'map', 'reduce',
    'find', 'any', 'all', 'unique', 'call', 'jsonParse', 'jsonStringify',
    'tomlParse', 'tomlStringify', 'xmlParse', 'xmlStringify', 'process', 'createApiStore',
    'osName', 'osArchitecture', 'osWorkingDirectory', 'terminalIsInteractive',
    'terminalSupportsColor',
    'textContains', 'textFind', 'textSlice',
    'textReplace', 'textSplit', 'textTrim', 'textLower', 'textUpper']
    .map(word => [word, vscode.CompletionItemKind.Function, 'Kyna standard-library function']),
  ['fs', vscode.CompletionItemKind.Module, 'Kyna filesystem namespace'],
  ['http', vscode.CompletionItemKind.Module, 'Kyna HTTP namespace'],
  ['json', vscode.CompletionItemKind.Module, 'Kyna JSON namespace'],
  ['toml', vscode.CompletionItemKind.Module, 'Kyna TOML namespace'],
  ['xml', vscode.CompletionItemKind.Module, 'Kyna XML namespace'],
  ['os', vscode.CompletionItemKind.Module, 'Injected operating-system information'],
  ['terminal', vscode.CompletionItemKind.Module, 'Injected terminal information'],
  ['db', vscode.CompletionItemKind.Module, 'Kyna parameterized SQL namespace'],
  ['collections', vscode.CompletionItemKind.Module, 'Kyna collection algorithms namespace']
];

const namespaceMembers = {
  console: ['log'],
  process: ['json', 'stringify', 'run', 'env'],
  fs: ['read', 'write', 'readJson', 'writeJson', 'createDirectory', 'exists', 'remove', 'list'],
  http: ['fetch', 'tryFetch', 'server', 'response', 'json', 'redirect'],
  json: ['parse', 'stringify'],
  toml: ['parse', 'stringify'],
  xml: ['parse', 'stringify'],
  os: ['name', 'architecture', 'cwd'],
  terminal: ['interactive', 'supportsColor'],
  db: ['query', 'execute'],
  collections: ['map', 'reduce', 'find', 'any', 'all', 'unique']
};


module.exports = { wordCompletions, namespaceMembers };
